### ISSUE TITLE
PlugIns not being copied by your macdeployqt

### ISSUE THREAD

**Issue by m0vse** [crystalidea/macdeployqt-universal#1]
Hi, 

I have just tried your process for creating a universal binary and I noticed that none of the PlugIns are copied for either the x64 and arm64 builds.

I tried the original macdeployqt on the x64 build and that then correctly created the PlugIns directory.

Any ideas?

Cheers

Phil

**Comment by m0vse** [comment]
I am closing this as I think it didn't like the path I had Qt in. I was using ~/Qt when I changed it to /Users/xxx/Qt it worked fine! Thanks for your work on this.

Phil

**Comment by kleuter** [comment]
thanks for the follow up, great that it works!
