### ISSUE TITLE
compiling qt_arm on intel Mac encounter "Bad CPU type in executable"

### ISSUE THREAD

**Issue by wzh4464** [crystalidea/macdeployqt-universal#2]
My configure command is
```
./configure -prefix /opt/local/Qt_arm -release -opensource -opengl -nomake examples -nomake tests QMAKE_APPLE_DEVICE_ARCHS=arm64
```
and when running 
```
make
```
I got
```
make[3]: /Users/zihanwu/qt5/qtbase/bin/moc: Bad CPU type in executable
make[3]: *** [.moc/moc_qabstractanimation.cpp] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [sub-corelib-make_first] Error 2
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtbase-make_first] Error 2
```
Do you have any ideas about this? Thank you!

**Comment by kleuter** [comment]
./configure -device-option QMAKE_APPLE_DEVICE_ARCHS=arm64 -opensource -confirm-license -nomake examples -nomake tests -no-openssl -securetransport -prefix /usr/local/Qt-5.15.2-arm

[Source](https://github.com/crystalidea/qt-build-tools/blob/master/5.15.2/compile_mac_arm_cross.sh)
